### ISSUE TITLE
hardcode

### ISSUE THREAD

**Issue by DenProgrammer** [polvanovvgosh/wp-site#2]
https://github.com/polvanovvgosh/wp-site/blob/50a5cc2d0824ff99f59a572ea7dbb50c23b26349/wp-content/themes/storefront-child/functions.php#L14

такие данные нельзя хранить в гите, надо добавить сеттинг в настройки темы/сайта, и хранить в базе

**Comment by polvanovvgosh** [comment]
Fixed
